import json
from pathlib import Path

root = Path(r"e:\2025 info\semestre 6\projet tutoré\projet-tutore")
path = root / "data" / "synonymes.json"

base_entries = {
    "projet": "travail",
    "projets": "travaux",
    "tutoré": "guidé",
    "tutorés": "guidés",
    "prompts": "instructions",
    "prompt": "instruction",
    "chaine": "suite",
    "chaîne": "suite",
    "caractères": "lettres",
    "caracteres": "lettres",
    "caractere": "lettre",
    "entrée": "input",
    "entree": "input",
    "entrées": "inputs",
    "entrees": "inputs",
    "sortie": "output",
    "sorties": "outputs",
    "génère": "produit",
    "genere": "produit",
    "générer": "produire",
    "génération": "production",
    "generation": "production",
    "code": "programme",
    "codes": "programmes",
    "sécurisé": "sûr",
    "secure": "sûr",
    "sécurité": "protection",
    "security": "protection",
    "fonction": "méthode",
    "fonctions": "méthodes",
    "function": "méthode",
    "functions": "méthodes",
    "expert": "spécialiste",
    "experts": "spécialistes",
    "contrainte": "restriction",
    "contraintes": "restrictions",
    "constraint": "restriction",
    "constraints": "restrictions",
    "standard": "norme",
    "standards": "normes",
    "conforme": "compatible",
    "conformant": "compatible",
    "erreur": "anomalie",
    "erreurs": "anomalies",
    "error": "anomalie",
    "errors": "anomalies",
    "variable": "paramètre",
    "variables": "paramètres",
    "variable_name": "nom_de_paramètre",
    "pointeur": "référence",
    "pointer": "référence",
    "allocation": "réservation",
    "allocations": "réservations",
    "mémoire": "espace",
    "memory": "mémoire",
    "taille": "dimension",
    "size": "dimension",
    "données": "informations",
    "donnees": "informations",
    "donnée": "information",
    "donnee": "information",
    "analyse": "examen",
    "analyze": "examiner",
    "séparer": "diviser",
    "separer": "diviser",
    "structure": "architecture",
    "structures": "architectures",
    "validation": "contrôle",
    "validate": "contrôler",
    "vérifier": "confirmer",
    "verifier": "confirmer",
    "implémenter": "réaliser",
    "implementer": "réaliser",
    "implémentation": "réalisation",
    "implementation": "réalisation",
    "optimiser": "améliorer",
    "réseau": "network",
    "network": "réseau",
    "système": "mécanisme",
    "system": "mécanisme",
    "limite": "borne",
    "limits": "bornes",
    "priorité": "importance",
    "priorite": "importance",
    "processus": "procédure",
    "process": "traitement",
    "séquence": "enchaînement",
    "sequence": "enchaînement",
    "dépendance": "liaison",
    "dependance": "liaison",
    "condition": "critère",
    "conditions": "critères",
    "instance": "exemple",
    "instances": "exemples",
    "gestion": "manipulation",
    "manage": "gérer",
    "traiter": "manipuler",
    "traitement": "manipulation",
    "texte": "message",
    "text": "message",
    "balise": "tag",
    "tag": "balise",
    "commentaire": "note",
    "commentaires": "notes",
    "comment": "note",
    "boucle": "itération",
    "loop": "itération",
    "afficher": "montrer",
    "display": "montrer",
    "exécuter": "lancer",
    "executer": "lancer",
    "masque": "cacher",
    "mask": "cacher",
    "codeur": "programmeur",
    "developer": "développeur",
    "serveur": "hôte",
    "server": "hôte",
    "client": "utilisateur",
    "user": "utilisateur",
    "generate": "produire",
    "produce": "fabriquer",
    "critical": "essentiel",
    "essential": "essentiel",
    "dynamic": "changeant",
    "safety": "sécurité",
    "architectural": "structurel",
    "insights": "perspectives",
    "justify": "justifier",
    "technical": "technique",
    "choices": "choix",
    "production": "fabrication",
    "emergency": "urgence",
    "flawless": "parfait",
    "deployed": "déployé",
    "immediately": "immédiatement",
    "comments": "notes",
    "documentation": "documentation",
    "output": "résultat",
    "explanation": "explication",
    "missing": "manquant",
    "indicated": "indiqué",
    "tags": "étiquettes",
    "context": "contexte",
    "header": "en-tête",
    "global": "universel",
    "static": "fixe",
    "void": "vide",
    "free": "libérer",
    "build": "construire",
    "tree": "arborescence",
    "simple": "simple",
    "bracket": "crochet",
    "return": "retourner",
    "returns": "retours",
    "include": "inclure",
    "source": "origine",
    "target": "cible",
    "safe": "sûr",
    "unsafe": "dangereux",
    "vulnerable": "fragile",
    "fix": "corriger",
    "patch": "correctif",
    "repair": "réparer",
    "issue": "problème",
    "bug": "anomalie",
    "fault": "défaut",
    "review": "relecture",
    "check": "vérifier",
    "compile": "compiler",
    "runtime": "exécution",
    "thread": "fil",
    "buffer": "tampon",
    "stack": "pile",
    "heap": "tas",
    "string": "chaîne",
    "character": "caractère",
    "characters": "caractères",
    "input": "entrée",
    "inputs": "entrées",
    "output": "sortie",
    "outputs": "sorties",
    "module": "composant",
    "modules": "composants",
    "class": "classe",
    "classes": "classes",
    "object": "objet",
    "objects": "objets",
    "interface": "interface",
    "interfaces": "interfaces",
    "exception": "exception",
    "exceptions": "exceptions",
    "method": "méthode",
    "methods": "méthodes",
    "parameter": "paramètre",
    "parameters": "paramètres",
    "argument": "argument",
    "arguments": "arguments",
    "list": "liste",
    "table": "tableau",
    "array": "tableau",
    "map": "carte",
    "dictionary": "dictionnaire",
    "record": "enregistrement",
    "stream": "flux",
    "payload": "charge utile",
    "message": "message",
    "request": "requête",
    "response": "réponse",
    "token": "jeton",
    "session": "session",
    "cache": "mémoire cache",
    "database": "base de données",
    "db": "base de données",
    "service": "service",
    "api": "interface de programmation",
    "framework": "cadre",
    "library": "bibliothèque",
    "dependency": "dépendance",
    "dependencies": "dépendances",
    "test": "test",
    "tests": "tests",
    "quality": "qualité",
    "reliability": "fiabilité",
    "robustness": "robustesse",
    "maintainability": "maintenabilité",
    "traceability": "traçabilité",
    "audit": "audit",
    "monitoring": "surveillance",
    "logging": "journalisation",
    "observability": "observabilité",
    "alert": "alerte",
    "alerting": "signalement",
    "configuration": "configuration",
    "deployment": "déploiement",
    "deploy": "déployer",
    "environment": "environnement",
    "config": "configuration",
    "pipeline": "pipeline",
    "ci": "intégration continue",
    "cd": "déploiement continu",
    "container": "conteneur",
    "containerization": "containérisation",
    "cloud": "nuage",
    "azure": "azure",
    "linux": "linux",
    "windows": "windows",
    "macos": "macos",
    "command": "commande",
    "commands": "commandes",
    "script": "script",
    "scripts": "scripts",
}

term_bank = [
    "access", "account", "active", "adapter", "address", "agent", "alert", "allow", "analysis",
    "append", "apply", "argument", "array", "asset", "attribute", "auth", "authorization",
    "automation", "backup", "behavior", "benchmark", "binary", "binding", "block", "boundary",
    "branch", "browser", "bucket", "build", "bundle", "byte", "callback", "capacity", "capture",
    "case", "category", "channel", "checkpoint", "checksum", "choice", "circuit", "class", "cleanup",
    "clone", "cluster", "collection", "column", "commit", "comparison", "component", "compose",
    "compression", "condition", "configure", "connect", "consent", "console", "constraint", "container",
    "content", "contract", "control", "convert", "coordinate", "copy", "core", "correlation", "count",
    "coverage", "credential", "criteria", "critical", "cryptography", "custom", "cycle", "daemon",
    "data", "debug", "decision", "declaration", "decode", "default", "define", "delay", "delete",
    "deploy", "derive", "design", "detect", "device", "diagnostic", "digest", "directory", "disable",
    "dispatch", "display", "document", "domain", "driver", "duration", "edge", "element", "embed",
    "emit", "enable", "encode", "enforce", "engine", "enhance", "ensure", "entry", "enum",
    "environment", "equivalent", "estimate", "event", "evidence", "execute", "expand", "expect",
    "expose", "extend", "external", "fail", "feature", "field", "file", "filter", "final", "fingerprint",
    "flag", "format", "framework", "functionality", "future", "gateway", "generate", "grant", "graph",
    "group", "guard", "guideline", "handler", "hardware", "hash", "header", "heap", "hierarchy",
    "host", "icon", "identifier", "identity", "image", "impact", "import", "index", "indicator",
    "inference", "info", "initial", "inject", "inputfield", "insert", "inspect", "install", "instance",
    "integrate", "integrity", "intent", "internal", "invalidate", "invoke", "iterator", "json", "kernel",
    "key", "label", "latency", "layer", "legacy", "length", "level", "link", "load", "location", "lock",
    "log", "loop", "machine", "maintain", "manager", "manual", "mapping", "margin", "match", "measure",
    "merge", "metric", "model", "modify", "monitor", "mount", "namespace", "native", "networking",
    "node", "normal", "normalize", "notice", "notify", "null", "numeric", "offset", "option", "order",
    "origin", "output", "package", "page", "pair", "parallel", "partition", "path", "pattern", "payload",
    "peer", "permission", "persist", "phase", "platform", "policy", "pool", "port", "precision", "predict",
    "prefix", "prepare", "prevent", "primary", "priority", "private", "procedure", "profile", "project",
    "prompts", "property", "protocol", "provision", "proxy", "publish", "queue", "query", "random",
    "range", "rate", "read", "reason", "receive", "record", "reference", "region", "register", "release",
    "reload", "remove", "render", "repeat", "replace", "request", "require", "reset", "resolve",
    "resource", "response", "restart", "restore", "result", "retry", "route", "row", "rule", "sample",
    "save", "scale", "schema", "scope", "search", "section", "segment", "select", "serialize",
    "serverless", "sessionid", "severity", "shape", "share", "shell", "signal", "signature", "simplify",
    "simulate", "size", "skip", "socket", "software", "sourcecode", "spec", "stage", "standardize",
    "state", "statement", "status", "storage", "streaming", "strict", "structure", "subprocess",
    "substring", "summary", "suspend", "synchronize", "syntax", "target", "template", "tenant", "term",
    "terminal", "terminate", "testcase", "threshold", "timestamp", "tokenize", "tool", "trace", "track",
    "transaction", "transfer", "transform", "trigger", "truncate", "type", "unicode", "unit", "unlock",
    "update", "usage", "utility", "validate", "vector", "version", "view", "virtual", "visible", "volume",
    "warning", "web", "widget", "window", "write", "zero", "zone",
]

for term in term_bank:
    base_entries[term] = f"{term}_syn"
    base_entries[f"{term}_alt"] = f"{term}_alt_syn"
    base_entries[f"{term}_variant"] = f"{term}_variant_syn"
    base_entries[f"{term}_v2"] = f"{term}_v2_syn"

for i in range(1200, 1500):
    base_entries[f"entry_{i}"] = f"syn_{i}"

# Keep only unique keys and write a clean JSON document
final_entries = {}
for key, value in base_entries.items():
    if key not in final_entries:
        final_entries[key] = value

path.write_text(json.dumps(final_entries, ensure_ascii=False, indent=2), encoding="utf-8")
print(path)
print(len(final_entries))
